name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: [3.7]
    steps:
      - name: Install dependencies
        run: |
          pip install tox
      - name: Run tests
        run: |
          tox -e py37 -v
